version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile.prod
      target: production
    container_name: gpustack-ui-backend-prod
    ports:
      - "8001:8001"
    environment:
      - ENV=production
      - GPUSTACK_API_BASE=http://192.168.1.231:80
      - GPUSTACK_API_TOKEN=gpustack_d832b8eaabea94da_367798f8b89db33600d335d622531e1b
      - JWT_SECRET_KEY=${JWT_SECRET_KEY:-your-super-secret-jwt-key-change-in-production}
      - LOG_LEVEL=info
      - WORKERS=4
    volumes:
      - ./logs:/app/logs
      - ./uploads:/app/uploads
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - gpustack-network

  # Frontend is now served directly by the backend at /app

  # Redis for caching and session storage (optional)
  redis:
    image: redis:7-alpine
    container_name: gpustack-ui-redis-prod
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    networks:
      - gpustack-network

  # Nginx load balancer and reverse proxy
  nginx:
    image: nginx:alpine
    container_name: gpustack-ui-nginx-prod
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.prod.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - gpustack-network

volumes:
  redis_data:
    driver: local

networks:
  gpustack-network:
    driver: bridge
