services:
  backend:
    build: ./backend
    ports:
      - "8001:8000"
    environment:
      - TAVILY_API_KEY=${TAVILY_API_KEY}
      - GPUSTACK_API_URL=${GPUSTACK_API_URL}
      - GPUSTACK_API_KEY=${GPUSTACK_API_KEY}
    volumes:
      - ./backend:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    image: nginx:alpine
    ports:
      - "3000:80"
    volumes:
      - ./frontend/public:/usr/share/nginx/html:ro
    depends_on:
      - backend

