services:
  backend:
    build: 
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - "8001:8000"
    environment:
      - ENV=development
    volumes:
      - ./.env:/app/.env:ro
      - ./.env.local:/app/.env.local:ro
    # Multiple workers for better concurrency
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --workers 3
    # Resource limits for better stability
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M


